### PR TITLE
Bugfix/dashboard

### PR DESCRIPTION
**Pull request by mmahdigh**
- Fixing the tokens/collectibles containers
- Minor aesthetic changes in the dashboard
- Adding copy to clipboard upon clicking on the profile section (top left of the screen)
- Making the promotion box swipe-able

### CODE REVIEW

**Comment by mmahdigh** [comment]
#28

**Review by mateodaza — CHANGES_REQUESTED** [review]
@mmahdigh can you take a look at the conflicts, I moved the Tokens + Collectible Balance section to a reusable component

**Comment by MoeNick** [comment]
@mmahdigh @jainkrati 
Mateo asked for some changes last week. Can we push it?

**Comment by mmahdigh** [comment]
@mateodaza  Make sure nothing breaks due to the changes in the `UserBalance`. You had removed setting selected tokens and collectibles which I brought back. You also had added an `action` prop which was not called anywhere. I imagine you'd want to disable the token/collectible detail modal if the component is used in the deposit/send sections but I wasn't 100% sure.

Feel free to add your commits to this branch today and tomorrow so @maryjaf  can test all these fixes by Sunday.

**Review by mateodaza — APPROVED** [review]
@yussdev added minor changes for the user balance, thanks

**Review by jainkrati — APPROVED** [review]

**Pull request merged**
